# Global 全局配置
site_analytics: <!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-YEK9RFHCSV"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-YEK9RFHCSV');</script>
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: ./images/site-logo.png
snow: false
click_animate_js: 'candy'
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
check_update: true

vendors:
  packages:
    disqusjs: 
      version: 1.2.6
    gitalk: 
      version: 1.7.2
    gitment: 
      version: 0.0.3
    twikoo: 
      version: 1.5.11
    valine: 
      version: 1.4.18
    "@waline/client": 
      version: 1.6.0
    bootstrap: 
      version: 3.3.4
    nprogress: 
      version: 0.2.0
    aplayer: 
      version: 1.10.1
    "@fancyapps/fancybox": 
      version: 3.5.7
    clipboard: 
      version: 2.0.6
    layui-src: 
      version: 2.5.5
    font-awesome: 
      version: 4.7.0
    jquery: 
      version: 3.6.0
    qrcode_js: 
      version: 1.0.0
    mermaid: 
      version: 9.1.1
    meting:
      version: 2.0.1

# 自定义样式
customStyles:
  images: # 图片相关设置
    banner: /images/banner.webp # 站点横幅
    background: /images/bg.webp # 站点背景

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  archives: /archives/
  bangumis: /bangumis/
  music: /music/
  charts: /charts/
  theme: https://github.com/Candinya/Kratos-Rebirth
  sites:
    submenu: true
    friends: /friends/
    links: /links/
  search: /search/

label:
  index: <i class="fa fa-home"></i>首頁
  archives: <i class="fa fa-book"></i>歸檔
  bangumis: <i class="fa fa-television"></i>追劇
  music: <i class="fa fa-music"></i>音樂相關
  charts: <i class="fa fa-area-chart"></i>統計
  theme: <i class="fa fa-info-circle"></i>主題來源
  sites:
    submenu: <i class="fa fa-bookmark"></i>網站
    friends: <i class="fa fa-bolt"></i>大神
    links: <i class="fa fa-heart"></i>好康的
  search: <i class="fa fa-search"></i>

# Footer 页脚配置
group_link: 
contact:
  weibo: 
  mail: 
  telegram: 
  twitter: db5nGez2VL9wHZj
  facebook: 
  linkedin: 
  fediverse:
    instance: 
    username: 
  github: XChiChiX
  rss:
timenotice: 本站已運行
icp: 
psr:
  
# Post Page 文章页配置
posts:
  show_cc: false
  donate: false
  share: false
  comments: 
    provider: 'waline'
    enableBGImage: false

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/reference/client.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: https://blog-api-8c9u8y6af-xchichix.vercel.app/ #后端服务器地址，必填
  visitor: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitalk 文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitalk:
  clientID: 'GitHub Application Client ID'
  clientSecret: 'GitHub Application Client Secret'
  repo: 'Kratos-Rebirth-Demo'
  owner: 'Candinya'
  admin: 
    - 'Candinya'
  distractionFreeMode: false

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitment 文档](https://github.com/imsun/gitment#methods) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitment:
  owner: 'Candinya'
  repo: 'Kratos-Rebirth-Demo'
  oauth:
    client_id: 'Your client ID'
    client_secret: 'Your client secret'

# LiveRe [LiveRe](https://livere.com/) 评论相关
livere:
  id: city
  uid:

# APlayer 左下角音乐播放器
aplayer:
  enabled: true
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 945133400
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: /images/marin.gif
mobile_toc: 
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    cover:
      randomAmount: 20 # 表示从1~20
      baseUrl: null # 使用默认值（不单独配置），将跟随 vendors 中的相关设定选择是否使用 cdn
      filenameTemplate: "thumb_{no}.webp" 
    createTime: "2022/01/28 00:00:00"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: dC3goDG6FN50UOqD6MM1mVNvbMxlVe5rAdIupH_wn6g
  baidu: 
  bing: 

# Friends 友链相关内容
friends:
  href: ""
  page:
    title: "大神的網站"
    comments: true
    description: "摁"
    updated: "2022-10-09"
  list:
  - name: "測試1"
    bio: "星爆"
    avatar: "/images/avatar.webp"
    link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  - name: "測試2"
    bio: "氣流"
    avatar: "/images/avatar.webp"
    link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  - name: "測試3"
    bio: "斬"
    avatar: "/images/avatar.webp"
    link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  verify: true # 验证每个友链的可访问性，炸了会有提示

google_analytics: G-YEK9RFHCSV

# 统计图表，支持发布文章统计、发布日历、Top标签统计、分类统计、分类雷达。
# see https://www.npmjs.com/package/hexo-butterfly-charts
charts:
  enable: true # 是否启用功能
  postsChart:
    title: 文章發佈統計 # 设置文章发布统计的标题，默认为空
    interval: 1 # 横坐标间隔
  tagsChart:
    title: Top 10 標籤統計 # 设置标签统计的标题，默认为空
    interval: 1 # 横坐标间隔
  postsCalendar_Title: #文章发布日历 # 设置发布日历的标题，默认为空
  categoriesChart_Title: # 设置分类统计的标题，默认为空
  categoriesRadar_Title: # 设置分类雷达的标题，默认为空

tidio:
  enable: true
  key: houtiasuiwkwumofst66c7qu5e4czlb9